# Generated by Django 5.1.6 on 2025-03-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture'),
        ('users', '0002_rating'),
    ]

    operations = [
    ]
