# Generated by Django 5.1.6 on 2025-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
