# Generated by Django 5.1.6 on 2025-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowrequest_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
