# Generated by Django 5.1.6 on 2025-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_clothingitem_collections_alter_tag_category'),
        ('clothing_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item_collections', to='clothing.clothingitem'),
        ),
    ]
