# Generated by Django 5.1.6 on 2025-02-21 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_remove_clothingitem_user_clothingitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='availability_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('in_repair', 'In Repair')], default='checked_in', max_length=20),
        ),
    ]
