# Generated by Django 5.1.6 on 2025-02-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_clothingitem_availability_date_clothingitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
