# Generated by Django 5.1.6 on 2025-02-22 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_clothingitem_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='status',
            new_name='availability',
        ),
    ]
