# Generated by Django 5.1.6 on 2025-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_rename_status_clothingitem_availability'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to='users.userprofile'),
        ),
    ]
