# Generated by Django 5.1.6 on 2025-02-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_clothingitem_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tshirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Activewear', 'Activewear'), ('Jacket', 'Jacket'), ('Coat', 'Coat')], max_length=50)),
                ('size', models.CharField(blank=True, choices=[('xsmall', 'XS'), ('small', 'S'), ('med', 'M'), ('large', 'L'), ('xlarge', 'XL')], max_length=20, null=True)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='size',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.ManyToManyField(to='clothing.tag'),
        ),
    ]
