# Generated by Django 5.1.6 on 2025-02-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_tag_remove_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('Tshirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Activewear', 'Activewear'), ('Jacket', 'Jacket'), ('Coat', 'Coat')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='size',
            field=models.CharField(blank=True, choices=[('xsmall', 'XS'), ('small', 'S'), ('med', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('onesize', 'One Size')], max_length=20, null=True),
        ),
    ]
