# Generated by Django 5.1.6 on 2025-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0008_alter_tag_category_alter_tag_color_alter_tag_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clothing_images/'),
        ),
    ]
