# Generated by Django 5.1.6 on 2025-03-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0009_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='clothing.tag'),
        ),
    ]
