# Generated by Django 5.1.6 on 2025-03-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0010_alter_clothingitem_availability_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='clothing.tag'),
        ),
    ]
