# Generated by Django 5.1.6 on 2025-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0013_clothingitem_checked_out_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('Tshirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Activewear', 'Activewear'), ('Jacket', 'Jacket'), ('Coat', 'Coat'), ('Accessories', 'Accessories')], max_length=50, null=True),
        ),
    ]
