# Generated by Django 5.1.6 on 2025-03-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0013_clothingitem_checked_out_by'),
        ('clothing_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_items', to='clothing_collections.collection'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, choices=[('Tshirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Activewear', 'Activewear'), ('Jacket', 'Jacket'), ('Coat', 'Coat'), ('Accessories', 'Accessories')], max_length=50, null=True),
        ),
    ]
