# Generated by Django 5.1.6 on 2025-03-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_alter_tag_category'),
        ('clothing', '0014_clothingitem_collections_alter_tag_category'),
    ]

    operations = [
    ]
