# Generated by Django 5.1.6 on 2025-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
