# Generated by Django 5.1.6 on 2025-04-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0017_remove_clothingitem_likes_clothingitem_favorited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='favorited_by',
            new_name='likes',
        ),
    ]
