# Generated by Django 5.1.6 on 2025-04-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0017_clothingitem_location'),
        ('clothing', '0020_alter_clothingitem_likes'),
    ]

    operations = [
    ]
