# Generated by Django 5.1.6 on 2025-04-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0022_alter_clothingitem_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='likes',
            new_name='favorites',
        ),
    ]
