# Generated by Django 5.1.6 on 2025-04-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0024_alter_clothingitem_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='favorites',
            new_name='likes',
        ),
    ]
