# Generated by Django 5.1.6 on 2025-04-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0026_alter_clothingitem_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='location',
            field=models.CharField(default='UVA', max_length=100),
        ),
    ]
