# Generated by Django 5.1.6 on 2025-04-28 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0027_remove_clothingitem_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothing.clothingitem')),
            ],
        ),
    ]
