# Generated by Django 5.1.6 on 2025-02-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('in_repair', 'In Repair')], default='checked_in', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('availability_date', models.DateField()),
            ],
        ),
    ]
