# Generated by Django 5.1.6 on 2025-02-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_clothingitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='owner',
        ),
    ]
